schema-version = 2
release-version = "1.66.0-symphony.17.calibration"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.local]
registry = "localhost:5826"

[sdk]
name = "bottlerocket-sdk"
version = "0.79.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "9.2.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "17.0.1-symphony.17.build-5ab25fc6"

vendor = "local"
