schema-version = 2
release-version = "1.64.0"
project-vendor = "Bottlerocket"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.piyush]
registry = "public.ecr.aws/s2v1a1q8"

[sdk]
name = "bottlerocket-sdk"
version = "0.76.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "6.1.1"
vendor = "piyush"

[[kit]]
name = "bottlerocket-core-kit"
version = "15.0.0"
vendor = "piyush"
