schema-version = 1
release-version = "1.27.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.piyush]
registry = "533267423195.dkr.ecr.us-west-2.amazonaws.com"

[sdk]
name = "bottlerocket-sdk"
version = "0.45.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "3.1.1"
vendor = "piyush"
