schema-version = 1
release-version = "1.32.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.piyush]
registry = "public.ecr.aws/s2v1a1q8"

[sdk]
name = "bottlerocket-sdk"
version = "0.50.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "1.0.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "5.3.0"
vendor = "piyush"
