schema-version = 1
release-version = "1.30.0"

[vendor.bottlerocket]
registry = "public.ecr.aws/bottlerocket"

[vendor.piyush]
registry = "533267423195.dkr.ecr.us-west-2.amazonaws.com"

[sdk]
name = "bottlerocket-sdk"
version = "0.50.0"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-kernel-kit"
version = "1.0.2"
vendor = "bottlerocket"

[[kit]]
name = "bottlerocket-core-kit"
version = "5.3.0"
vendor = "piyush"
