# Metrics
[settings.metrics]
service-checks = ["apiserver", "chronyd", "containerd", "host-containerd", "docker"]

# Network
[metadata.settings.network]
affected-services = ["containerd", "docker", "host-containerd", "host-containers", "updog"]

# Image registry credentials
[metadata.settings.container-registry.credentials]
affected-services = ["host-containers", "bootstrap-containers", "thar-be-registries"]
