# Network
[metadata.settings.network]
affected-services = ["containerd", "host-containerd", "host-containers", "updog"]

# Image registry credentials
[metadata.settings.container-registry.credentials]
affected-services = ["host-containers", "bootstrap-containers", "thar-be-registries"]
